-- Seed data for Truth Hair D1 Database

-- Insert categories
INSERT INTO categories (id, name, slug, description) VALUES
('cat_human_hair', 'Human Hair Wigs', 'human-hair-wigs', 'Premium 100% human hair wigs'),
('cat_synthetic', 'Synthetic Wigs', 'synthetic-wigs', 'High-quality synthetic fiber wigs'),
('cat_lace_front', 'Lace Front Wigs', 'lace-front-wigs', 'Natural hairline lace front wigs'),
('cat_full_lace', 'Full Lace Wigs', 'full-lace-wigs', 'Versatile full lace construction'),
('cat_closures', 'Closures & Frontals', 'closures-frontals', 'Hair closures and frontals'),
('cat_bundles', 'Hair Bundles', 'hair-bundles', 'Virgin hair bundles and extensions'),
('cat_360_lace', '360 Lace Wigs', '360-lace-wigs', '360 degree lace wigs'),
('cat_u_part', 'U-Part Wigs', 'u-part-wigs', 'U-part wigs for natural blending');

-- Insert sample products
INSERT INTO products (
  id, name, slug, description, price, compare_at_price, sku,
  hair_type, quality, inches, density, texture, origin, color,
  cap_construction, cap_size, lace_type, parting_space,
  baby_hair, pre_plucked, bleached_knots,
  is_active, stock, status, featured, category_id,
  seo_title, seo_description, tags
) VALUES 
(
  'prod_001',
  'Brazilian Body Wave Wig',
  'brazilian-body-wave-wig',
  'Luxurious Brazilian human hair wig with natural body wave pattern. Pre-plucked hairline with baby hair for realistic appearance.',
  299.99,
  399.99,
  'BWW-001',
  'HUMAN_HAIR',
  'PREMIUM',
  '["12", "14", "16", "18", "20", "22"]',
  '130%',
  'Body Wave',
  'Brazilian',
  'Natural Black',
  'Lace Front',
  'Medium',
  'HD Lace',
  'Free Part',
  1, 1, 0,
  1, 15, 'ACTIVE', 1,
  'cat_human_hair',
  'Brazilian Body Wave Human Hair Wig | Truth Hair',
  'Premium Brazilian body wave wig made from 100% human hair.',
  '["brazilian", "body wave", "human hair", "lace front"]'
),
(
  'prod_002',
  'Straight Bob Lace Front',
  'straight-bob-lace-front',
  'Chic straight bob style lace front wig. Perfect for everyday wear with minimal styling required.',
  189.99,
  249.99,
  'SBL-001',
  'SYNTHETIC',
  'STANDARD',
  '["10", "12", "14"]',
  '150%',
  'Straight',
  'Synthetic',
  'Jet Black',
  'Lace Front',
  'Medium',
  'Swiss Lace',
  'Middle Part',
  0, 1, 0,
  1, 24, 'ACTIVE', 1,
  'cat_lace_front',
  'Straight Bob Lace Front Wig | Truth Hair',
  'Stylish straight bob lace front wig. Easy to wear and maintain.',
  '["bob", "straight", "lace front", "synthetic"]'
),
(
  'prod_003',
  'Curly Afro Full Lace',
  'curly-afro-full-lace',
  'Beautiful curly afro texture full lace wig. Versatile styling options with 360-degree natural hairline.',
  459.99,
  599.99,
  'CAF-001',
  'HUMAN_HAIR',
  'LUXURY',
  '["14", "16", "18", "20"]',
  '180%',
  'Kinky Curly',
  'Peruvian',
  'Natural Black',
  'Full Lace',
  'Medium',
  'HD Lace',
  '360 Degree',
  1, 1, 1,
  1, 8, 'ACTIVE', 1,
  'cat_full_lace',
  'Curly Afro Full Lace Wig | Truth Hair',
  'Premium curly afro full lace wig with 360-degree styling versatility.',
  '["afro", "curly", "full lace", "human hair"]'
),
(
  'prod_004',
  'Deep Wave Bundle Deal',
  'deep-wave-bundle-deal',
  '3 bundles of virgin deep wave hair. Available in lengths from 12" to 30". Can be dyed and styled.',
  249.99,
  329.99,
  'DWB-001',
  'HUMAN_HAIR',
  'PREMIUM',
  '["12", "14", "16", "18", "20", "22", "24", "26", "28", "30"]',
  'Standard',
  'Deep Wave',
  'Malaysian',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0, 0, 0,
  1, 20, 'ACTIVE', 0,
  'cat_bundles',
  'Deep Wave Hair Bundle Deal | Truth Hair',
  'Virgin deep wave hair bundles, 3-piece set.',
  '["bundles", "deep wave", "virgin hair", "extensions"]'
),
(
  'prod_005',
  'HD Lace Closure 4x4',
  'hd-lace-closure-4x4',
  'Ultra-thin HD lace closure for seamless blend. Pre-plucked with natural hairline.',
  89.99,
  129.99,
  'HDC-001',
  'HUMAN_HAIR',
  'PREMIUM',
  '["4x4"]',
  'Standard',
  'Multiple',
  'Indian',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0, 0, 0,
  1, 30, 'ACTIVE', 0,
  'cat_closures',
  'HD Lace Closure 4x4 | Truth Hair',
  'High-definition lace closure with pre-plucked hairline.',
  '["closure", "hd lace", "4x4", "human hair"]'
),
(
  'prod_006',
  'Water Wave Synthetic Wig',
  'water-wave-synthetic-wig',
  'Affordable water wave synthetic wig with natural appearance. Heat-resistant fibers up to 180°C.',
  79.99,
  119.99,
  'WWS-001',
  'HEAT_FRIENDLY',
  'BASIC',
  '["18", "20", "22", "24"]',
  '150%',
  'Water Wave',
  'Synthetic',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0, 0, 0,
  1, 35, 'ACTIVE', 0,
  'cat_synthetic',
  'Water Wave Synthetic Wig | Truth Hair',
  'Beautiful water wave pattern synthetic wig.',
  '["synthetic", "water wave", "affordable", "heat resistant"]'
),
(
  'prod_007',
  'Blonde Balayage Lace Front',
  'blonde-balayage-lace-front',
  'Stunning blonde balayage human hair lace front wig. Hand-painted highlights for natural sun-kissed look.',
  389.99,
  499.99,
  'BBL-001',
  'HUMAN_HAIR',
  'LUXURY',
  '["16", "18", "20", "22", "24"]',
  '150%',
  'Straight',
  'European',
  'Blonde Balayage',
  NULL,
  NULL,
  NULL,
  NULL,
  0, 0, 0,
  1, 5, 'ACTIVE', 1,
  'cat_lace_front',
  'Blonde Balayage Lace Front Wig | Truth Hair',
  'Luxury blonde balayage human hair wig with hand-painted highlights.',
  '["blonde", "balayage", "human hair", "lace front", "european"]'
),
(
  'prod_008',
  'Short Pixie Cut Wig',
  'short-pixie-cut-wig',
  'Trendy short pixie cut wig with tapered sides. Low maintenance style perfect for active lifestyle.',
  149.99,
  199.99,
  'SPC-001',
  'BLEND',
  'STANDARD',
  '["6", "8"]',
  '130%',
  'Straight',
  'Mixed',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0, 0, 0,
  1, 18, 'ACTIVE', 0,
  'cat_synthetic',
  'Short Pixie Cut Wig | Truth Hair',
  'Stylish short pixie cut wig with human hair blend.',
  '["pixie", "short", "blend", "low maintenance"]'
);